# Generated by Django 2.2 on 2019-05-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('epa_number', models.CharField(max_length=50)),
                ('rui', models.TextField()),
                ('rei', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
