# Generated by Django 2.2 on 2019-08-09 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polyname', models.CharField(max_length=200, null=True)),
                ('polyList', models.TextField(null=True)),
                ('rectBounds', models.TextField(null=True)),
                ('newLat', models.CharField(max_length=50, null=True)),
                ('newLng', models.CharField(max_length=50, null=True)),
                ('areaRect', models.CharField(max_length=50, null=True)),
                ('areaPoly', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrant_name', models.CharField(blank=True, max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('epa_number', models.CharField(max_length=50)),
                ('active_ingredient', models.CharField(blank=True, max_length=100)),
                ('rui', models.TextField()),
                ('rei', models.DateTimeField(blank=True, null=True)),
                ('use', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.TextField(null=True)),
                ('lng', models.TextField(null=True)),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('license_no', models.IntegerField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocationPesticide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('rate', models.CharField(max_length=50, null=True)),
                ('target', models.CharField(max_length=50, null=True)),
                ('applicator', models.CharField(max_length=50, null=True)),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rup.Pesticide')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rup.Location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rup.UserProfile'),
        ),
        migrations.CreateModel(
            name='Formulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(null=True)),
                ('pesticide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rup.Pesticide')),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
