# Generated by Django 2.2 on 2019-05-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0002_applicator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticide',
            name='use',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
