# Generated by Django 2.2 on 2019-05-09 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0003_pesticide_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pesticide',
            name='purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rup.Purpose'),
        ),
    ]
