# Generated by Django 2.2 on 2019-05-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0004_auto_20190509_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesticide',
            name='purpose',
        ),
        migrations.DeleteModel(
            name='Purpose',
        ),
    ]
