# Generated by Django 2.2 on 2019-05-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0006_name_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('epa_number', models.CharField(max_length=50)),
                ('rui', models.TextField()),
                ('rei', models.DateTimeField(blank=True, null=True)),
                ('use', models.CharField(max_length=50, null=True)),
                ('siteNames', models.CharField(max_length=50)),
                ('siteColors', models.CharField(max_length=50)),
            ],
        ),
    ]
