# Generated by Django 2.2 on 2019-05-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0009_auto_20190515_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationpesticide',
            old_name='pesticide_id',
            new_name='pesticide',
        ),
        migrations.RenameField(
            model_name='locationpesticide',
            old_name='user_id',
            new_name='user',
        ),
    ]
