# Generated by Django 2.2 on 2019-05-16 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0010_auto_20190516_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationpesticide',
            name='name',
        ),
        migrations.AddField(
            model_name='locationpesticide',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rup.Location'),
            preserve_default=False,
        ),
    ]
