# Generated by Django 2.2 on 2019-05-17 17:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0011_auto_20190516_1749'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='location',
            managers=[
                ('restricted', django.db.models.manager.Manager()),
            ],
        ),
    ]
