# Generated by Django 2.2 on 2019-05-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0012_auto_20190517_1754'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='location',
            managers=[
            ],
        ),
    ]
