# Generated by Django 2.2 on 2019-06-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0014_auto_20190521_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polyname', models.CharField(max_length=200)),
                ('polyList', models.TextField()),
                ('rectBounds', models.TextField()),
                ('newLat', models.CharField(max_length=50)),
                ('newLng', models.CharField(max_length=50)),
                ('areaRect', models.CharField(max_length=50)),
                ('areaPoly', models.CharField(max_length=50)),
            ],
        ),
    ]
