# Generated by Django 2.2 on 2019-06-22 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0015_userlocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
