# Generated by Django 2.2 on 2019-07-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0017_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpesticide',
            name='applicator',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='locationpesticide',
            name='rate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='locationpesticide',
            name='target',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
