# Generated by Django 2.2 on 2019-07-01 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0018_auto_20190701_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationpesticide',
            name='applicator',
        ),
    ]
