# Generated by Django 2.2 on 2019-07-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0019_remove_locationpesticide_applicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpesticide',
            name='applicator',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
