# Generated by Django 2.2 on 2019-07-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0020_locationpesticide_applicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userCenter', models.TextField()),
            ],
        ),
    ]
