# Generated by Django 2.2 on 2019-07-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0021_center'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='userCenter',
            new_name='user_center',
        ),
    ]
