# Generated by Django 2.2 on 2019-07-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0023_auto_20190706_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='user_center',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
