# Generated by Django 2.2 on 2019-07-07 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rup', '0024_center_user_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='user_center',
        ),
        migrations.AddField(
            model_name='center',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
