# Generated by Django 2.2.3 on 2019-07-15 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0026_auto_20190706_2028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Center',
        ),
    ]
