# Generated by Django 2.2.3 on 2019-07-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0027_delete_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('lat', models.TextField(null=True)),
                ('lng', models.TextField(null=True)),
            ],
        ),
    ]
